GET http://localhost:5050/ HTTP/1.1
###
GET https://localhost:5050/ HTTP/1.1
###
GET http://localhost:5050/record HTTP/1.1
###
GET https://localhost:5050/record HTTP/1.1
###
POST https://localhost:5050/record HTTP/1.1
###
PATCH  https://localhost:5050/record HTTP/1.1


###
POST https://localhost:5050/user/signup HTTP/1.1
Content-Type: application/json

{
    "username": "Uzi786",
    "password": "Uzi786"  
}

###
POST https://localhost:5050/user/login HTTP/1.1
Content-Type: application/json

{
    "username": "Uzi786",
    "password": "Uzi786"  
}

###
DELETE  https://localhost:5050/record/6523e65d2066fca11ea5e4be HTTP/1.1
content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhc2gxNyIsInBhc3N3b3JkIjoiU2FzaDEyMzQiLCJpYXQiOjE2OTY4NDg3NTQsImV4cCI6MTY5Njg1MjM1NH0.olbtAnSmhV03VJPWdXllGz1QjD7pjIJab8HsSwliuqc

###
POST https://localhost:5050/record/create HTTP/1.1
content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhc2gxNyIsInBhc3N3b3JkIjoiU2FzaDEyMzQiLCJpYXQiOjE2OTY4NTE0NzksImV4cCI6MTY5Njg1NTA3OX0.59-7_1KAiqFbCn9_I05Dm47YXSLKIuDdRYgIpxh9l9Y

{
    "name":"recoooord"
}

###
PATCH  https://localhost:5050/record/6523efd83de8650c4c0c58a0 HTTP/1.1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNhc2gxNyIsInBhc3N3b3JkIjoiU2FzaDEyMzQiLCJpYXQiOjE2OTY4NTE0NzksImV4cCI6MTY5Njg1NTA3OX0.59-7_1KAiqFbCn9_I05Dm47YXSLKIuDdRYgIpxh9l9Y
content-Type: application/json

{
    "name":"test"
}

###
GET https://localhost:5050/record HTTP/1.1
content-Type: application/json



